server:
  port: 8081

spring:
  application:
    name: account
  datasource:
    url: jdbc:h2:mem:bank_accounts_db;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/Account-ms-openapi.yaml
    disable-swagger-default-url: true
