openapi: 3.0.3
info:
  description: API de cuentas para Banking-MS
  title: Account Microservice API
  version: 1.0.0
servers:
- url: http://localhost:8082
paths:
  /cuentas:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BankAccount'
                type: array
          description: Lista de cuentas
      summary: Listar cuentas
      tags:
      - Cuentas
      x-accepts:
      - application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
          description: Cuenta creada (saldo inicial 0.0)
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error de negocio o validación
      summary: Crear cuenta
      tags:
      - Cuentas
      x-content-type: application/json
      x-accepts:
      - application/json
  /cuentas/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: Eliminada
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: No encontrado
      summary: Eliminar cuenta
      tags:
      - Cuentas
      x-accepts:
      - application/json
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
          description: Cuenta
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: No encontrado
      summary: Obtener cuenta por id
      tags:
      - Cuentas
      x-accepts:
      - application/json
  /cuentas/{id}/depositar:
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmountRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
          description: Saldo actualizado
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error de negocio
      summary: Depositar a la cuenta
      tags:
      - Cuentas
      x-content-type: application/json
      x-accepts:
      - application/json
  /cuentas/{id}/retirar:
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmountRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
          description: Saldo actualizado
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Regla de negocio (ahorros >= 0; corriente >= -500)
      summary: Retirar de la cuenta
      tags:
      - Cuentas
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    AccountType:
      enum:
      - AHORROS
      - CORRIENTE
      type: string
    BankAccount:
      example:
        balance: 6.027456183070403
        clienteId: 5
        overdraftLimit: 1.4658129805029452
        id: 0
        accountNumber: accountNumber
        type: AHORROS
      properties:
        id:
          format: int64
          type: integer
        accountNumber:
          type: string
        balance:
          format: double
          type: number
        type:
          $ref: '#/components/schemas/AccountType'
        overdraftLimit:
          format: double
          type: number
        clienteId:
          format: int64
          type: integer
      required:
      - accountNumber
      - balance
      - clienteId
      - id
      - overdraftLimit
      - type
      type: object
    CreateAccountRequest:
      example:
        clienteId: 0
        tipoCuenta: AHORROS
      properties:
        clienteId:
          format: int64
          type: integer
        tipoCuenta:
          $ref: '#/components/schemas/AccountType'
      required:
      - clienteId
      - tipoCuenta
      type: object
    AmountRequest:
      example:
        monto: 1.0800828190461012
      properties:
        monto:
          format: double
          minimum: 1
          type: number
      required:
      - monto
      type: object
    ErrorResponse:
      example:
        code: code
        message: message
        errors:
          key: errors
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          additionalProperties:
            type: string
          type: object
      type: object

