openapi: 3.0.3
info:
  title: Client API
  version: 1.0.0
  description: API para la gesti칩n de clientes bancarios
  contact:
    name: Nataly Gir칩n
    email: nataly@example.com

servers:
  - url: http://localhost:8080
    description: Servidor local de desarrollo

paths:
  /clientes:
    post:
      summary: Crear cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClientRequest'
      responses:
        '201':
          description: Cliente creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '400':
          description: Datos inv치lidos
    get:
      summary: Listar todos los clientes
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientResponse'

  /clientes/{id}:
    get:
      summary: Obtener cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '404':
          description: Cliente no encontrado

    put:
      summary: Actualizar cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClientRequest'
      responses:
        '200':
          description: Cliente actualizado
        '400':
          description: Datos inv치lidos
        '404':
          description: Cliente no encontrado

    delete:
      summary: Eliminar cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Cliente eliminado
        '409':
          description: Cliente tiene cuentas activas
        '404':
          description: Cliente no encontrado

components:
  schemas:
    CreateClientRequest:
      type: object
      properties:
        firstName: { type: string }
        lastName: { type: string }
        email: { type: string, format: email }
        dni: { type: string }
      required: [firstName, lastName, email, dni]

    UpdateClientRequest:
      type: object
      properties:
        firstName: { type: string }
        lastName: { type: string }
        email: { type: string, format: email }

    ClientResponse:
      type: object
      properties:
        id: { type: integer }
        firstName: { type: string }
        lastName: { type: string }
        email: { type: string }
        dni: { type: string }
